# Generated by Django 4.2.11 on 2024-03-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
